### ISSUE TITLE
question: how to set next order number

### ISSUE THREAD

**Issue by boelle** [mauran/Woocommerce-delete-all-orders#8]
so i used the sql commands to delete orders

but is there a way to set the next order number?

mine keeps climbing up,

with all order numbers i would expect it to start from 1 or at least a lower number

**Comment by mauran** [comment]
I haven't done Wordpress or Woocommerce for a couple of years. I Googled a bit, and i guess this is the SQL command you'll need. I haven't tested it out, so please only do this on a local development environment or something similar. **Not production.**

`ALTER TABLE wp_posts AUTO_INCREMENT = 1`

Please tell it if that worked for you.

**Comment by boelle** [comment]
it kind of worked

proble is that order numbers are based on post number so you have to be carefull

in my case i remember the first order number was 85 as the last post id was 84

and if you add a product or change a product that changes the post id too, this is also why order numbers in woocommerce does not come in sequence but there are plugins that can take care of that

i only found out this after i posted here

you could argue that  the people behind woocommerce could have made it use seqential numbers out the box but i just take it as it is what it is

**Comment by andrija-naglic** [comment]
> `ALTER TABLE wp_posts AUTO_INCREMENT = 1`

I **definitely** wouldn't mess with the standard WordPress tables' setup!

@boelle I guess you are stuck with order number being post ID, because indeed that's what it is.

Your best bet is going for a custom meta field for that post type and use that.
For example, in my country, the government requires you to follow the invoice numbering rule and all the invoices should follow the same pattern AA-BB-CC where AA is the incremental sequential number starting from 1 for the current year.

No way WooCommerce guys could have taken all such cases into an account :)

**Comment by boelle** [comment]
Hi

I would have the same problem, ie orders number have to be sequential but they dont have to start from 1

my idea would only be a temp "fix" while doing testing

the best bet here is to use a pluging, but i tried that and they did not work. but together with what i found out it should be able to keep the ship floating while the plugin issue gets sorted

**Comment by mauran** [comment]
I guess that this issue is resolved. So i'll just close it for now :)
